### PR TITLE
chore(doc):Setup API documentation using swagger

### PR DESCRIPTION
**Pull request by alaintresor**
#### What does this PR do?
Initial setup for the project API documentation using swagger 

#### How should this be manually tested?
After cloning the repo, cd into it and Run npm install and after Run npm run start:dev . Open browser then enter this URL "http://localhost:3000/api/docs/"

#### What are the relevant pivotal tracker stories?
##182201712

### CODE REVIEW

**Review by semy-tuyi — DISMISSED** [review]

**Review by joshwambere — DISMISSED** [review]
@alaintresor, LGTM

**Review by uwambajeddy — DISMISSED** [review]
@alaintresor Looks good to me

**Review by Placide123 — DISMISSED** [review]

**Review by didasmbalanya — CHANGES_REQUESTED** [review]
Add a test api on the root endpoint to test it works

**Comment by alaintresor** [comment]
Screenshot (28)
Screenshot (27)

**Review by joshwambere — APPROVED** [review]

**Review by didasmbalanya — APPROVED** [review]

**Pull request merged**
