### PR TITLE
Chore-deploy-heroku#182201713

### PR DESCRIPTION
**Pull request by Patricknshimiyimana**

### CODE REVIEW

**Review by Placide123 — DISMISSED** [review]

**Review by Placide123 — DISMISSED** [review]
good morning patrick, use ES6 to write index.js but other are working fine. Well done.

**Review by uwambajeddy — COMMENTED** [review]
Looks good but this is supposed to be a work in progress because this will later be is Es6 and there will other more changes.

**Comment by Patricknshimiyimana** [comment]
> good morning patrick, use ES6 to write index.js but other are working fine. Well done.

Done. Thanks!!

**Comment by Patricknshimiyimana** [comment]
> Looks good but this is supposed to be a work in progress because this will later be is Es6 and there will other more changes.

Now it is ready.

**Review by semy-tuyi — APPROVED** [review]

**Review by joshwambere — APPROVED** [review]
@Patricknshimiyimana  LTGM

**Review by didasmbalanya — APPROVED** [review]

**Pull request merged**
